openapi: 3.0.0
info:
  title: Math API
  description: API for performing arithmetic operations and user login for JWT authentication
  version: 1.0.0
servers:
  - url: /
paths:
  /math/calculate:
    post:
      summary: Perform an arithmetic operation
      operationId: calculate
      parameters:
        - name: operation
          in: header
          description: "The operation to be performed (add, subtract, multiply, divide)"
          required: true
          schema:
            type: string
            enum:
              - add
              - subtract
              - multiply
              - divide
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/math_calculate_body'
        required: true
      responses:
        "200":
          description: Successfully returns the result
          content:
            application/json:
              schema:
                type: number
        "400":
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
        - bearerAuth: []   # Apply JWT auth only to /math/calculate
      x-swagger-router-controller: MathController

  /auth/login:
    post:
      summary: User login to obtain JWT token
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        "200":
          description: Login successful, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
        "400":
          description: Bad request (missing or invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        "401":
          description: Unauthorized (invalid credentials)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        "500":
          description: Internal server error
      x-swagger-router-controller: AuthController
components:
  schemas:
    math_calculate_body:
      required:
        - a
        - b
      type: object
      properties:
        a:
          type: number
        b:
          type: number

    login_body:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
          description: "User's username"
        password:
          type: string
          description: "User's password"

    error_response:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
