openapi: 3.0.0
info:
  title: Math API
  description: API for performing arithmetic operations and user login for JWT authentication
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HASAN_7/calculator_api/1.0.0
  - url: /

paths:
  /math/calculate:
    post:
      summary: Perform an arithmetic operation
      operationId: calculate
      parameters:
        - name: operation
          in: header
          description: "The operation to be performed (add, subtract, multiply, divide)"
          required: true
          schema:
            type: string
            enum:
              - add
              - subtract
              - multiply
              - divide
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/math_calculate_body'
        required: true
      responses:
        "200":
          description: Successfully returns the result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                example:
                  result: 10
        "400":
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Invalid input. Both 'a' and 'b' must be numbers."
                status: 400
        "401":
          description: Unauthorized (missing or invalid token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Unauthorized. JWT token is missing or invalid."
                status: 401
        "403":
          description: Forbidden (Invalid token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Invalid or expired token."
                status: 403
        "415":
          description: Unsupported media type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Unsupported Media Type. Please use 'application/json'."
                status: 415
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Internal server error. Please try again later."
                status: 500
      security:
        - bearerAuth: []  # Use bearerAuth for JWT
      x-swagger-router-controller: MathController

  /auth/login:
    post:
      summary: User login to obtain JWT token
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        "200":
          description: Login successful, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
                example:
                  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "400":
          description: Bad request (missing or invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Invalid input. Both 'username' and 'password' must be provided."
                status: 400
        "401":
          description: Unauthorized (invalid credentials)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Invalid username or password."
                status: 401
        "415":
          description: Unsupported media type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Unsupported Media Type. Please use 'application/json'."
                status: 415
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
              example:
                message: "Internal server error. Please try again later."
                status: 500
      x-swagger-router-controller: AuthController

components:
  schemas:
    math_calculate_body:
      required:
        - a
        - b
      type: object
      properties:
        a:
          type: number
          description: "First number for the operation"
        b:
          type: number
          description: "Second number for the operation"

    login_body:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
          description: "User's username"
        password:
          type: string
          description: "User's password"

    error_response:
      type: object
      properties:
        message:
          type: string
          description: "Error message detailing what went wrong."
        status:
          type: integer
          description: "HTTP status code indicating the error type."

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
